### ISSUE TITLE
Can't train voxnet - config file loading fails

### ISSUE THREAD

**Issue by NatholBMX** [dimatura/voxnet#13]
Hi there,

whenever I try to train the network with the provided config file, I receive following error:
```

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    main(args)
  File "train.py", line 126, in main
    config_module = imp.load_source("config", args.config_path)
  File "C:\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\imp.py", line 171, in loa
d_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1577, in get_code
  File "<frozen importlib._bootstrap>", line 672, in _code_to_bytecode
ValueError: unmarshallable object
```

**Comment by maflcko** [comment]
> python-3.4.4

This script does not work with python3

**Comment by xidianxiaofeixian** [comment]
> Hi there,
> 
> whenever I try to train the network with the provided config file, I receive following error:
> 
> ```
> 
> Traceback (most recent call last):
>   File "train.py", line 184, in <module>
>     main(args)
>   File "train.py", line 126, in main
>     config_module = imp.load_source("config", args.config_path)
>   File "C:\WinPython-32bit-3.4.4.5Qt5\python-3.4.4\lib\imp.py", line 171, in loa
> d_source
>     module = methods.load()
>   File "<frozen importlib._bootstrap>", line 1220, in load
>   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1129, in _exec
>   File "<frozen importlib._bootstrap>", line 1467, in exec_module
>   File "<frozen importlib._bootstrap>", line 1577, in get_code
>   File "<frozen importlib._bootstrap>", line 672, in _code_to_bytecode
> ValueError: unmarshallable object
> ```

Has this problem been solved?

**Comment by fast-squid** [comment]
I'm having a same problem.

i can't load the config file with python3
but it is also not available to install path module in python2

anyone solved this issue?
