### ISSUE TITLE
When test use  shapenet10_weights.npz',Failed to interpret file Path(u'shapenet10_weights.npz') as a pickle

### ISSUE THREAD

**Issue by MissLikeWind** [dimatura/voxnet#21]

**Comment by iElric** [comment]
I receive the same error as well.  This issue has also been mentioned by issue #11 
Can someone please help? I've attached the error text.

wangyexin@wangyexin-PC:~/下载/voxnet-master/scripts$ python test.py --weights shapenet10_weights.npz config/shapenet10.py shapenet10_test.tar --out-fname out.npz
ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
/usr/local/lib/python2.7/dist-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
2017-04-25 17:24:14,322 INFO| Loading weights from shapenet10_weights.npz
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    main(args)
  File "test.py", line 75, in main
    voxnet.checkpoints.load_weights(args.weights_fname, model['l_out'])
  File "/home/wangyexin/下载/voxnet-master/scripts/voxnet/checkpoints.py", line 39, in load_weights
    param_dict = np.load(fname)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 401, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file Path(u'shapenet10_weights.npz') as a pickle

**Comment by MissLikeWind** [comment]
I find the solution to the problem. You can see the file shapenet10_weights.npz , it is not the data file. You should use the git lfs to download the data of weights from the web mentioned in the file shapenet10_weights.npz。

**Comment by iElric** [comment]
sorry I am relatively new to git, I don't know if i understand you correctly. Please correct me if i was wrong. I use atom to open shapenet10_weights.npz, and i find this url:https://git-lfs.github.com/spec/v1. So i need to download from this url to obtain the weights using git lfs?

**Comment by MissLikeWind** [comment]
@rabbit23,You can use the command git, or download the data directly from github.

**Comment by iElric** [comment]
Thank you very much. I understand how to solve this, it seems that if i clone from github, I can not obtain the correct this data file.Thank your very much! May i ask have you met this error: Namerror: global name'HostFromGpu' is not defined.
I noticed this may be a result of not having cuda. So i guess if i don't have Nvida gpu, I can not run this test. Am i right?

**Comment by MissLikeWind** [comment]
@rabbit23.       Sorry,I have not met the problem. Cuda is recommended and required for gpu code generation on Theano.May be you just use CPU, I don't know whether it works.

**Comment by iElric** [comment]
Thank you！May i konw your cuda version?  Are you using cuda 8 or other version? I notice that in this voxnet project, any version differences  may result in error. Since you finished test, i want to use the same version as yours. Thanks for your help!

**Comment by buemi** [comment]
I received the same error even if I downloaded the "shapenet10_weights.npz" file from GIT. Any suggestion?
