### ISSUE TITLE
IOError: Failed to interpret file Path(u'weights.npz') as a pickle

### ISSUE THREAD

**Issue by wolfbill** [dimatura/voxnet#3]
Hi:
 I've met a problem when I run  ”python test.py config/shapenet10.py shapenet10_test.tar --out-fname out.npz.“
The details about the problem list below：
nal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
2016-07-28 18:25:41,842 INFO| Loading weights from weights.npz
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    main(args)
  File "test.py", line 75, in main
    voxnet.checkpoints.load_weights(args.weights_fname, model['l_out'])
  File "/root/voxnet-master/voxnet/checkpoints.py", line 39, in load_weights
    param_dict = np.load(fname)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 384, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file Path(u'weights.npz') as a pickle

I have no idea about it 。

**Comment by wolfbill** [comment]
It's ok now

**Comment by dimatura** [comment]
Ok. Sometimes if one interrupts the program while the pickles are written they get corrupted.
